# Generated by Django 2.2.5 on 2019-10-06 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exhibits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='exhibit_picture_link',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='exhibit_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
